# Variables
@baseUrl = http://localhost:3333

# Health Check
GET {{baseUrl}}/health

###

# Get rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# Create room
# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
  "name": "Natan",
  "description": "A description for Room 1"
}
###

@roomId = {{createRoom.response.body.$.roomId}}

###

# Get room questions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# Create question
# @name createQuestion
POST {{baseUrl}}/rooms/253ffe83-c4c2-4c92-a50a-d9c244b68c85/questions
Content-Type: application/json

{
  "question": "Oque é react ?"
}